default: â‹¯

icons:
  ğŸ•:
    - 742
  ğŸŒ¾:
    - 763
  ğŸŒ±:
    - 780
  ğŸ“„:
    - 1520
  ğŸ› :
    - 1711
  ğŸ’¡:
    - 1731
  ğŸ§±:
    - 1740
  ğŸªš:
    - 1750
  ğŸ‘·:
    - 1761
    - 1771
    - 2791
  ğŸ“Š:
    - 1799
  ğŸ“°:
    - 2741
  ğŸ›:
    - 2842
    - 5931
  âœˆï¸:
    - [3000, 3299]
    - 4511
    - 4582
    - 4722
    - 4723
  ğŸš—:
    - [3351, 3441]
  ğŸ¨:
    - [3501, 3790]
  ğŸšˆ:
    - 4011
    - 4112
  â›´:
    - 4111
  ğŸ’Š:
    - 4119
    - 5912
  ğŸš–:
    - 4121
  ğŸšŒ:
    - 4131
  ğŸšš:
    - 4214
    - 4789
  ğŸ“¦:
    - 4215
    - 4225
  ğŸ›³:
    - 4411
  ğŸš¤:
    - 4457
  âš“ï¸:
    - 4468
  ğŸš¦:
    - 4784
  ğŸ“:
    - 4812
    - 4814
  ğŸ’¸:
    - 4829
  ğŸ¡:
    - 4900
  ğŸ›’:
    - 5411
    - 5499
  ğŸ¥©:
    - 5422
  ğŸ¬:
    - 5441
  ğŸ¥›:
    - 5451
  ğŸ°:
    - 5462
  ğŸ½:
    - 5812
  ğŸº:
    - 5813
    - 5921
  ğŸ•:
    - 5814
